# Generated by Django 5.0.2 on 2024-03-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast_details',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dinner_details',
            name='price',
        ),
        migrations.RemoveField(
            model_name='juice_details',
            name='price',
        ),
    ]
