# Generated by Django 5.0.2 on 2024-03-22 13:41

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0002_remove_breakfast_details_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast_details',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
        migrations.AddField(
            model_name='dinner_details',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
        migrations.AddField(
            model_name='juice_details',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
    ]
